name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull UoB-SWE7303-DevOps/todo-flask:latest
    - name: Delete Old docker container
      run: sudo docker rm -f todo-flask-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name todo-flask-container UoB-SWE7303-DevOps/todo-flask
